Fix to work with current grunt (see below)
So I just did a pull of AngularFun and installed it on a virgin machine.
Apparently there is an issue with grunt that breaks "grunt dev" (see
below).  For newer versions of grunt options.base is an array rather than
a string.  I applied the recommended fix and now everything works great
for me.

(I'm an angular/JS noob, so perhaps this fix is not ideal - but thanks
for the super great template - it is really helping me get started)

For details on the grunt issue:
https://github.com/gruntjs/grunt-contrib-connect/issues/41


kevinh@kevin-think:~/development/AngularFun$ grunt dev
Running "clean:working" (clean) task
Cleaning .temp...OK
Cleaning dist...OK

Running "coffeelint:app" (coffeelint) task
>> 14 files lint free.

Running "copy:app" (copy) task
Created 16 directories, copied 78 files

Running "jade:views" (jade) task

Running "jade:spa" (jade) task

Running "shimmer:dev" (shimmer) task
remaining backend/gitHubBackend.coffee
remaining backend/peopleBackend.coffee
remaining backend/viewsBackend.coffee
remaining controllers/gitHubController.coffee
remaining controllers/personController.coffee
remaining controllers/searchHistoryController.coffee
remaining directives/tab.coffee
remaining directives/tabs.coffee
remaining filters/twitterfy.coffee
remaining interceptors/dispatcher.coffee
remaining routes.coffee
remaining services/gitHubService.coffee
remaining services/messageService.coffee
remaining services/personService.coffee

Running "coffee:app" (coffee) task
File .temp/scripts/app.js created.
File .temp/scripts/app.js.map created (source map).
File .temp/scripts/backend/gitHubBackend.js created.
File .temp/scripts/backend/gitHubBackend.js.map created (source map).
File .temp/scripts/backend/peopleBackend.js created.
File .temp/scripts/backend/peopleBackend.js.map created (source map).
File .temp/scripts/backend/viewsBackend.js created.
File .temp/scripts/backend/viewsBackend.js.map created (source map).
File .temp/scripts/bootstrap.js created.
File .temp/scripts/bootstrap.js.map created (source map).
File .temp/scripts/controllers/gitHubController.js created.
File .temp/scripts/controllers/gitHubController.js.map created (source map).
File .temp/scripts/controllers/personController.js created.
File .temp/scripts/controllers/personController.js.map created (source map).
File .temp/scripts/controllers/searchHistoryController.js created.
File .temp/scripts/controllers/searchHistoryController.js.map created (source map).
File .temp/scripts/directives/tab.js created.
File .temp/scripts/directives/tab.js.map created (source map).
File .temp/scripts/directives/tabs.js created.
File .temp/scripts/directives/tabs.js.map created (source map).
File .temp/scripts/filters/twitterfy.js created.
File .temp/scripts/filters/twitterfy.js.map created (source map).
File .temp/scripts/interceptors/dispatcher.js created.
File .temp/scripts/interceptors/dispatcher.js.map created (source map).
File .temp/scripts/main.js created.
File .temp/scripts/main.js.map created (source map).
File .temp/scripts/routes.js created.
File .temp/scripts/routes.js.map created (source map).
File .temp/scripts/services/gitHubService.js created.
File .temp/scripts/services/gitHubService.js.map created (source map).
File .temp/scripts/services/messageService.js created.
File .temp/scripts/services/messageService.js.map created (source map).
File .temp/scripts/services/personService.js created.
File .temp/scripts/services/personService.js.map created (source map).

Running "less:app" (less) task
File .temp/styles/styles.css created: 0 B → 121.88 kB

Running "template:indexDev" (template) task

Running "copy:dev" (copy) task
Created 13 directories, copied 116 files

Running "connect:app" (connect) task
connect.multipart() will be removed in connect 3.0
visit https://github.com/senchalabs/connect/wiki/Connect-3.0 for alternatives
connect.limit() will be removed in connect 3.0
Started connect web server on http://localhost:40062

Running "watch" task
Waiting...
TypeError: Object /home/kevinh/development/AngularFun/dist has no method 'charAt'
  at exports.normalize (path.js:336:27)
  at SendStream.root.SendStream.from (/home/kevinh/development/AngularFun/node_modules/express/node_modules/send/lib/send.js:116:16)
  at Object.staticMiddleware [as handle] (/home/kevinh/development/AngularFun/node_modules/express/node_modules/connect/node_modules/serve-static/index.js:80:8)
  at next (/home/kevinh/development/AngularFun/node_modules/express/node_modules/connect/lib/proto.js:193:15)
  at next (/home/kevinh/development/AngularFun/node_modules/express/node_modules/connect/lib/proto.js:195:9)
  at Object.methodOverride [as handle] (/home/kevinh/development/AngularFun/node_modules/express/node_modules/connect/node_modules/method-override/index.js:48:5)
  at next (/home/kevinh/development/AngularFun/node_modules/express/node_modules/connect/lib/proto.js:193:15)
  at multipart (/home/kevinh/development/AngularFun/node_modules/express/node_modules/connect/lib/middleware/multipart.js:97:37)
  at /home/kevinh/development/AngularFun/node_modules/express/node_modules/connect/lib/middleware/bodyParser.js:64:9
  at urlencoded (/home/kevinh/development/AngularFun/node_modules/express/node_modules/connect/lib/middleware/urlencoded.js:40:37)
  at /home/kevinh/development/AngularFun/node_modules/express/node_modules/connect/lib/middleware/bodyParser.js:62:7
  at json (/home/kevinh/development/AngularFun/node_modules/express/node_modules/connect/lib/middleware/json.js:42:37)
  at Object.bodyParser [as handle] (/home/kevinh/development/AngularFun/node_modules/express/node_modules/connect/lib/middleware/bodyParser.js:60:5)
  at next (/home/kevinh/development/AngularFun/node_modules/express/node_modules/connect/lib/proto.js:193:15)
  at Object.logger (/home/kevinh/development/AngularFun/node_modules/express/node_modules/connect/node_modules/morgan/index.js:165:5)
  at next (/home/kevinh/development/AngularFun/node_modules/express/node_modules/connect/lib/proto.js:193:15)
  at Object.expressInit [as handle] (/home/kevinh/development/AngularFun/node_modules/express/lib/middleware.js:30:5)
  at next (/home/kevinh/development/AngularFun/node_modules/express/node_modules/connect/lib/proto.js:193:15)
  at Object.query [as handle] (/home/kevinh/development/AngularFun/node_modules/express/node_modules/connect/lib/middleware/query.js:45:5)
  at next (/home/kevinh/development/AngularFun/node_modules/express/node_modules/connect/lib/proto.js:193:15)
  at Function.app.handle (/home/kevinh/development/AngularFun/node_modules/express/node_modules/connect/lib/proto.js:201:3)
  at Object.fn [as handle] (/home/kevinh/development/AngularFun/node_modules/grunt-contrib-connect/node_modules/connect/lib/proto.js:73:14)
  at next (/home/kevinh/development/AngularFun/node_modules/grunt-contrib-connect/node_modules/connect/lib/proto.js:193:15)
  at Function.app.handle (/home/kevinh/development/AngularFun/node_modules/grunt-contrib-connect/node_modules/connect/lib/proto.js:201:3)
  at Object.fn [as handle] (/home/kevinh/development/AngularFun/node_modules/grunt-contrib-connect/node_modules/connect/lib/proto.js:73:14)
  at next (/home/kevinh/development/AngularFun/node_modules/grunt-contrib-connect/node_modules/connect/lib/proto.js:193:15)
  at Object.livereload [as handle] (/home/kevinh/development/AngularFun/node_modules/grunt-contrib-connect/node_modules/connect-livereload/index.js:147:5)
  at next (/home/kevinh/development/AngularFun/node_modules/grunt-contrib-connect/node_modules/connect/lib/proto.js:193:15)
  at Function.app.handle (/home/kevinh/development/AngularFun/node_modules/grunt-contrib-connect/node_modules/connect/lib/proto.js:201:3)
  at Server.app (/home/kevinh/development/AngularFun/node_modules/grunt-contrib-connect/node_modules/connect/lib/connect.js:65:37)
  at Server.EventEmitter.emit (events.js:98:17)
  at HTTPParser.parser.onIncoming (http.js:2108:12)
  at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:121:23)
  at Socket.socket.ondata (http.js:1966:22)
  at TCP.onread (net.js:527:27)

GET / 500 8ms - 4kb
TypeError: Object /home/kevinh/development/AngularFun/dist has no method 'charAt'
  at exports.normalize (path.js:336:27)
  at SendStream.root.SendStream.from (/home/kevinh/development/AngularFun/node_modules/express/node_modules/send/lib/send.js:116:16)
  at Object.staticMiddleware [as handle] (/home/kevinh/development/AngularFun/node_modules/express/node_modules/connect/node_modules/serve-static/index.js:80:8)
  at next (/home/kevinh/development/AngularFun/node_modules/express/node_modules/connect/lib/proto.js:193:15)
  at next (/home/kevinh/development/AngularFun/node_modules/express/node_modules/connect/lib/proto.js:195:9)
  at Object.methodOverride [as handle] (/home/kevinh/development/AngularFun/node_modules/express/node_modules/connect/node_modules/method-override/index.js:48:5)
  at next (/home/kevinh/development/AngularFun/node_modules/express/node_modules/connect/lib/proto.js:193:15)
  at multipart (/home/kevinh/development/AngularFun/node_modules/express/node_modules/connect/lib/middleware/multipart.js:97:37)
  at /home/kevinh/development/AngularFun/node_modules/express/node_modules/connect/lib/middleware/bodyParser.js:64:9
  at urlencoded (/home/kevinh/development/AngularFun/node_modules/express/node_modules/connect/lib/middleware/urlencoded.js:40:37)
  at /home/kevinh/development/AngularFun/node_modules/express/node_modules/connect/lib/middleware/bodyParser.js:62:7
  at json (/home/kevinh/development/AngularFun/node_modules/express/node_modules/connect/lib/middleware/json.js:42:37)
  at Object.bodyParser [as handle] (/home/kevinh/development/AngularFun/node_modules/express/node_modules/connect/lib/middleware/bodyParser.js:60:5)
  at next (/home/kevinh/development/AngularFun/node_modules/express/node_modules/connect/lib/proto.js:193:15)
  at Object.logger (/home/kevinh/development/AngularFun/node_modules/express/node_modules/connect/node_modules/morgan/index.js:165:5)
  at next (/home/kevinh/development/AngularFun/node_modules/express/node_modules/connect/lib/proto.js:193:15)
  at Object.expressInit [as handle] (/home/kevinh/development/AngularFun/node_modules/express/lib/middleware.js:30:5)
  at next (/home/kevinh/development/AngularFun/node_modules/express/node_modules/connect/lib/proto.js:193:15)
  at Object.query [as handle] (/home/kevinh/development/AngularFun/node_modules/express/node_modules/connect/lib/middleware/query.js:45:5)
  at next (/home/kevinh/development/AngularFun/node_modules/express/node_modules/connect/lib/proto.js:193:15)
  at Function.app.handle (/home/kevinh/development/AngularFun/node_modules/express/node_modules/connect/lib/proto.js:201:3)
  at Object.fn [as handle] (/home/kevinh/development/AngularFun/node_modules/grunt-contrib-connect/node_modules/connect/lib/proto.js:73:14)
  at next (/home/kevinh/development/AngularFun/node_modules/grunt-contrib-connect/node_modules/connect/lib/proto.js:193:15)
  at Function.app.handle (/home/kevinh/development/AngularFun/node_modules/grunt-contrib-connect/node_modules/connect/lib/proto.js:201:3)
  at Object.fn [as handle] (/home/kevinh/development/AngularFun/node_modules/grunt-contrib-connect/node_modules/connect/lib/proto.js:73:14)
  at next (/home/kevinh/development/AngularFun/node_modules/grunt-contrib-connect/node_modules/connect/lib/proto.js:193:15)
  at Object.livereload [as handle] (/home/kevinh/development/AngularFun/node_modules/grunt-contrib-connect/node_modules/connect-livereload/index.js:94:14)
  at next (/home/kevinh/development/AngularFun/node_modules/grunt-contrib-connect/node_modules/connect/lib/proto.js:193:15)
  at Function.app.handle (/home/kevinh/development/AngularFun/node_modules/grunt-contrib-connect/node_modules/connect/lib/proto.js:201:3)
  at Server.app (/home/kevinh/development/AngularFun/node_modules/grunt-contrib-connect/node_modules/connect/lib/connect.js:65:37)
  at Server.EventEmitter.emit (events.js:98:17)
  at HTTPParser.parser.onIncoming (http.js:2108:12)
  at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:121:23)
  at Socket.socket.ondata (http.js:1966:22)
  at TCP.onread (net.js:527:27)

GET /favicon.ico 500 3ms - 4kb